M48
; DRILL file {KiCad (6.0.2)} date Mon Apr 25 23:22:51 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-25T23:22:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0248
%
G90
G05
T1
X5.1535Y-5.378
T2
X4.9173Y-5.378
X5.1535Y-5.378
T0
M30
